  
# Config file for automatic testing at travis-ci.org

sudo: true
language: python
notifications:
  email:  me@hikmatu.com
matrix:
    include:
      - python: 2.7
      - python: 3.4
      - python: 3.5
      - python: 3.6
      - python: 3.7
      - python: 3.8
      - python: 3.9
install:
  - pip install -r requirements.txt
