  
# Config file for automatic testing at travis-ci.org

sudo: true
language: python
notifications:
  email:  me@hikmatu.com
matrix:
    include:
      - python: 3.9
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=./
