from setuptools import setup

setup(
    name='Workday Webservices Client',
    version='0.1.0',
    description='This script will be expose all workday webservice operations',
    url='https://github.com/hikmat30ce/Workday-Webservices-Client.git',
    author='Hikmat Ullah',
    author_email='me@hikmatu.com',
    license='MIT License',
    packages=['human_resource'],
    install_requires=['mpi4py>=2.0',
                      'numpy',
                      'appdirs==1.4.4',
                      'attrs==20.3.0',
                      'cached-property==1.5.2',
                      'certifi==2020.12.5',
                      'chardet==4.0.0',
                      'defusedxml==0.6.0',
                      'idna==2.10',
                      'isodate==0.6.0',
                      'lxml==4.6.2',
                      'pytz==2021.1',
                      'requests==2.25.1',
                      'requests-file==1.5.1',
                      'requests-toolbelt==0.9.1',
                      'six==1.15.0',
                      'SQLAlchemy==1.3.23',
                      'urllib3==1.26.3',
                      'xmltodict==0.12.0',
                      'zeep==4.0.0',
                      'pymysql==1.0.2'

                      ],

    classifiers=[
        'Development Status :: 1 - Planning',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
    ],
)
